version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - apt-get update
      - apt-get install -y jq
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.0.0.1744-linux.zip
      - unzip ./sonar-scanner-cli-4.0.0.1744-linux.zip
      - chmod +x $PWD/sonar-scanner-4.0.0.1744-linux/bin/sonar-scanner
      - export PATH=$PATH:$PWD/sonar-scanner-4.0.0.1744-linux/bin/
      - pip install pytest pytest-cov
      - pip install coverage

  build:
    commands:
      - echo Building Project
      - echo Running Python Tests
      #- python -m pytest Sample_Project/src/blog/tests.py --junitxml=xunit-reports/xunit-result.xml --cov=Sample_Project/src --cov-report xml:coverage-reports/coverage.xml
      - echo Generating Coverage Report
      #- sonar-scanner -Dsonar.organization=sonarqube-aws-codebuild -Dsonar.projectKey=sonarqube-aws-codebuild_sq-aws-test -Dsonar.sources=Sample_Project/src -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=4aa88ee0029a1b7705b2e7fd6418579157cd9150 -Dsonar.python.xunit.reportPath=xunit-reports/xunit-result.xml -Dsonar.python.coverage.reportPaths=coverage-reports/coverage.xml
      #- sleep 5
      #- curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=sonarqube-aws-codebuild_sq-aws-test > analysis.json
      #- cat analysis.json
      - echo Finished Building


reports:
  pytest_reports:
    files:
      - xunit-result.xml
    base-directory: xunit-reports
    file-format: XUNIT

# cache:
#   paths:
#     - "node_modules/**/*"
#     - "/root/.cache/pip
