version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - apt-get update
      - apt-get install -y jq
      # - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.0.0.1744-linux.zip
      # - unzip ./sonar-scanner-cli-4.0.0.1744-linux.zip
      # - chmod +x $PWD/sonar-scanner-4.0.0.1744-linux/bin/sonar-scanner
      # - export PATH=$PATH:$PWD/sonar-scanner-4.0.0.1744-linux/bin/
      - pip install pytest pytest-cov
      - pip install coverage

  build:
    commands:
      - echo Building Project
      - echo Running Python Tests
      - echo Finished Building


reports:
  pytest_reports:
    files:
      - xunit-result.xml
    base-directory: xunit-reports
    file-format: XUNIT

# cache:
#   paths:
#     - "node_modules/**/*"
#     - "/root/.cache/pip
